use tcc;

insert into produto (descricao_prod, nome_prod, tipo_prod, cor_prod, material_prod, tamanho_prod, estoque, preco) values
('Pulseira de couro trançado com fecho magnético. Perfeita para um estilo casual.',	'Pulseira de Couro Trançado',	'Pulseira',	'Marrom',	'Couro, Metal',	'Ajustável',	'20',	'49.90'),
('Pulseira elegante com pedras naturais variadas, ideal para ocasiões especiais.',	'Pulseira de Prata com Pedras Naturais',	'Pulseira',	'Prata, Variedade',	'Prata, Pedras Naturais',	'Ajustável',	'20',	'159.90'),
('Pulseira robusta de aço inoxidável, perfeita para uso diário com estilo moderno.',	'Pulseira de Aço Inoxidável',	'Pulseira',	'Prata',	'Aço inoxidável',	'Ajustável',	'20',	'79.90'),
('Pulseira artesanal de miçangas coloridas, ótima para um visual étnico.',	'Pulseira de Miçangas',	'Pulseira',	'Variedade',	'Miçangas, Fio de Nylon',	'Ajustável',	'20',	'29.90'),
('Pulseira charmosa com berloques variados, ideal para quem gosta de personalizar seu estilo.',	'Pulseira de Prata com Berloques',	'Pulseira',	'Prata',	'Prata',	'Ajustável',	'20',	'99.90'),
('Pulseira de couro com placa de identificação gravada, estilo utilitário.',	'Pulseira de Couro com Placa de Identificação',	'Pulseira',	'Preto',	'Couro, Metal',	'Ajustável',	'20',	'39.90'),
('Pulseira de contas de madeira, ideal para um visual natural e casual.',	'Pulseira de Madeira',	'Pulseira',	'Marrom, Natural',	'Madeira, Fio de Algodão',	'Ajustável',	'20',	'19.90'),
('Pulseira de couro com pingente de caveira, perfeita para um estilo punk.',	'Pulseira de Couro com Pingente',	'Pulseira',	'Marrom',	'Couro, Metal',	'Ajustável',	'20',	'34.90'),
('Pulseira elegante com pérolas cultivadas, ideal para eventos formais.',	'Pulseira de Prata com Pérolas',	'Pulseira',	'Prata, Branco',	'Prata, Pérolas',	'Ajustável',	'20',	'129.90'),
('Pulseira bordada à mão com detalhes coloridos, perfeita para um estilo boho.',	'Pulseira de Tecido Bordada',	'Pulseira',	'Variedade',	'Tecido, Fio de Algodão',	'Ajustável',	'20',	'24.90'),
('Anel clássico de ouro branco com diamante, ideal para ocasiões especiais.',	'Anel de Ouro Branco com Diamante',	'Anel',	'Branco',	'Ouro Branco, Diamante',	'Diversos',	'20',	'2499.00'),
('Anel elegante de prata com zircônia, perfeito para uso diário.',	'Anel de Prata com Zircônia',	'Anel',	'Prata',	' Prata, Zircônia',	'Ajustável',	'20',	'149.90'),
('Anel robusto de aço inoxidável, ideal para quem busca durabilidade e estilo.',	'Anel de Aço Inoxidável',	'Anel',	'Prata',	'Aço Inoxidável',	'Ajustável',	'20',	'69.90'),
('Anel moderno de tungstênio, extremamente resistente e confortável.',	'Anel de Tungstênio',	'Anel',	'Prata',	'Tungstênio',	'Ajustável',	'20',	'299.90'),
('Anel clássico de ouro amarelo, perfeito para celebrações especiais.',	'Anel de Ouro Amarelo',	'Anel',	'Amarelo, Dourado',	'Ouro Amarelo',	'Diversos',	'20',	'1899.90'),
('Anel boho chic com pedra natural, ótimo para um visual descontraído.',	'Anel de Prata com Pedra Natural',	'Anel',	'Prata, Variedade',	'Prata, Pedras Naturais',	'Ajustável',	'20',	'179.90'),
('Anel romântico de ouro rosé, ideal para ocasiões especiais.',	'Anel de Ouro Rosé',	'Anel',	'Rosé',	'Ouro Rosé',	'Diversos',	'20',	'2199.00'),
('Anel elegante de prata com topázio facetado, perfeito para eventos formais.',	'Anel de Prata com Topázio',	'Anel',	'Prata',	'Prata, Topázio',	'Ajustável',	'20',	'399.90'),
('Anel de titânio moderno e resistente, ideal para uso diário.',	'Anel de Titânio',	'Anel',	'Prata',	'Titânio',	'Ajustável',	'20',	'229.90'),
('Anel sofisticado de prata com safira, perfeito para quem busca elegância.',	'Anel de Prata com Safira',	'Anel',	'Prata, Azul',	'Prata, Safira',	'Ajustável',	'20',	'549.90'),
('Brinco clássico de pérola com acabamento em ouro, perfeito para eventos formais.',	'Brinco de Pérola',	'Brinco',	'Pérolas, Ouro',	'Branco, Dourado',	'Pequeno',	'20',	'399.00'),
('Brinco de argola clássico em prata, ideal para uso diário.',	'Brinco de Argola de Prata',	'Brinco',	'Prata',	'Prata',	'Médio',	'20',	'79.90'),
('Brinco elegante de ouro branco com diamante, ideal para ocasiões especiais.',	'Brinco de Ouro Branco com Diamante',	'Brinco',	'Branco',	'Ouro Branco, Diamante',	'Pequeno',	'20',	'1199.00'),
('Brinco delicado de prata com zircônia, perfeito para um visual sofisticado.',	'Brinco de Prata com Zircônia',	'Brinco',	'Prata',	' Prata, Zircônia',	'Pequeno',	'20',	'149.90'),
(' Brinco clássico de ouro amarelo, ótimo para celebrações especiais.',	'Brinco de Ouro Amarelo',	'Brinco',	'Amarelo, Dourado',	'Ouro Amarelo',	'Pequeno',	'20',	'899.00'),
('Brinco elegante de prata com pérola cultivada, ideal para eventos formais.',	'Brinco de Prata com Pérola',	'Brinco',	'Prata, Branco',	'Prata, Pérola',	'Pequeno',	'20',	'249.90'),
(' Brinco romântico de ouro rosé, perfeito para ocasiões especiais.',	'Brinco de Ouro Rosé',	'Brinco',	'Rosé',	'Ouro Rosé',	'Pequeno',	'20',	'1499.00'),
(' Brinco delicado de prata com topázio, ótimo para eventos formais.',	'Brinco de Prata com Topázio',	'Brinco',	'Prata, Azul',	'Prata, Topázio',	'Pequeno',	'20',	'349.00'),
('Brinco moderno de titânio, extremamente leve e confortável para uso diário.',	'Brinco de Titânio',	'Brinco',	'Prata',	'Titânio',	'Pequeno',	'20',	'179.90'),
('Brinco elegante de prata com ametista natural, ideal para quem busca uma pedra preciosa.',	'Brinco de Prata com Ametista',	'Brinco',	'Prata, Roxo',	'Prata, Ametista',	'Pequeno',	'20',	'449.90'),
('Colar clássico de pérolas com fecho em ouro, ideal para ocasiões formais.',	'Colar de Pérola',	'Colar',	'Branco, Dourado',	'Pérola, Ouro',	'Médio',	'20',	'799.00'),
('Colar delicado de prata com pingente de coração, perfeito para um presente romântico.',	'Colar de Prata com Pingente de Coração',	'Colar',	'Prata',	'Prata',	'Médio',	'20',	'149.90'),
('Colar luxuoso de ouro branco com diamante, ideal para uma noite especial.',	'Colar de Ouro Branco com Diamante',	'Colar',	'Branco',	'Ouro Branco, Diamante',	'Médio',	'20',	'4999.00'),
(' Colar elegante de prata com zircônia, perfeito para um visual sofisticado.',	'Colar de Prata com Zircônia',	'Colar',	'Prata',	'Prata, Zircônia',	'Médio',	'20',	'299.90'),
('Colar clássico de ouro amarelo, ideal para celebrar momentos especiais.',	'Colar de Ouro Amarelo',	'Colar',	'Amarelo, Dourado',	'Ouro Amarelo',	'Médio',	'20',	'2999.00'),
('Colar elegante de prata com pérola cultivada, perfeito para eventos formais.',	'Colar de Prata com Pérola',	'Colar',	'Prata, Branco',	'Prata, Pérola',	'Médio',	'20',	'499.90'),
('Colar romântico de ouro rosé, ideal para uma ocasião especial.',	'Colar de Ouro Rosé',	'Colar',	'Rosé',	'Ouro Rosé',	'Médio',	'20',	'3499.00'),
('Colar elegante de prata com topázio facetado, ótimo para eventos formais.',	'Colar de Prata com Topázio',	'Colar',	'Prata, Azul',	'Prata, Topázio',	'Médio',	'20',	'599.90'),
('Colar moderno de titânio, leve e confortável para uso diário.',	'Colar de Titânio',	'Colar',	'Prata',	'Titânio',	'Médio',	'20',	'349.90'),
('Colar elegante de prata com ametista natural, perfeito para quem aprecia pedras preciosas.',	'Colar de Prata com Ametista',	'Colar',	'Prata, Roxo',	'Prata, Ametista',	'Médio',	'20',	'899.90');
