use tcc;

insert into produto (descricao_prod, nome_prod, tipo_prod, cor_prod, material_prod, tamanho_prod, estoque, preco) values
('Pulseira elegante e simples com pingentes de olho grego.',	'Pulseira Olho Grego Folheada em Prata',	'Pulseira, Mais Vendidos',	'Azul Escuro, Azul Claro',	'Prata',	'Ajustável',	'20',	'12.00'),
('Pulseira elegante com pedras.',	'Pulseira Folheada em Prata com Pedrarias',	'Pulseira, Index',	'Preto, Rosa, Transparente',	'Prata, Joia',	'Ajustável',	'20',	'12.00'),
('Pulseira simples com ponto de luz com formato de estrela.',	'Pulseira Ponto de Luz Folheada em Prata com Pingente de Estrela',	'Pulseira, Index',	'Transparente',	'Prata',	'Ajustável',	'20',	'12.00'),
('Pulseira simples com pingentes de estrela.',	'Pulseira Folheada em Prata 5 Estrelas',	'Pulseira',	'Prata',	'Prata',	'Ajustável',	'20',	'12.00'),
('Pulseira simples com pedras transparentes.',	'Pulseira Folheada em Prata com Pedrarias Transparente',	'Pulseira, Index',	'Transparente',	'Prata, Joia',	'Ajustável',	'20',	'12.00'),
('Colar simples com pedras transparentes.',	'Colar Folheado em Prata com Pedrarias Transparente',	'Colar, Index',	'Transparente',	'Prata, Joia',	'Ajustável',	'20',	'15.00'),
('Conjunto simples com colar e brinco com ponto de luz, formato quadrado.',	'Conjunto Colar + Brinco Ponto de Luz Folheado em Prata com Formato Quadrado',	'Conjunto, Mais Vendidos',	'Prata',	'Prata, Joia',	'Ajustável',	'20',	'18.00'),
('Conjunto simples com colar e brinco com ponto de luz, formato de coração.',	'Conjunto Colar + Brinco Ponto de Luz Folheado em Prata com Formato Coração',	'Conjunto',	'Prata',	'Prata, Joia',	'Ajustável',	'20',	'18.00'),
('Pulseira simples com ponto de luz folheado em prata, formato de coração.',	'Pulseira Ponto de Luz Folheada em Prata com Formato Coração',	'Pulseira',	'Prata',	'Prata, Joia',	'Ajustável',	'20',	'12.00'),
('Colar simples e elegante com pedrarias transparentes.',	'Colar Folheado em Prata com Pedrarias Transparente',	'Colar, Index',	'Prata, Transparente',	'Prata, Joia',	'Ajustável',	'20',	'15.00'),
('Pulseira elegante de setas.',	'Pulseira Setas Folheada em Prata',	'Pulseira, Index',	'Prata',	'Prata',	'Ajustável',	'20',	'12.00'),
('Colar elegante de setas.',	'Colar Setas Folheado em Prata',	'Colar, Index',	'Prata',	'Prata',	'Ajustável',	'20',	'15.00'),
('Conjunto elegante com colar e pulseira de setas.',	'Conjunto Colar + Pulseira Setas Folheado em Prata',	'Conjunto',	'Prata',	'Prata',	'Ajustável',	'20',	'18.00'),
('Conjunto elegante com colar e pulseira de coração.',	'Conjunto Colar + Pulseira Coração Folheado em Prata',	'Conjunto',	'Prata',	'Prata',	'Ajustável',	'20',	'18.00'),
('Pulseira elegante com corações.',	'Pulseira Coração Folheado em Prata',	'Pulseira',	'Prata',	'Prata',	'Ajustável',	'20',	'12.00'),
('Colar elegante de corações.',	'Colar Coração Folheado em Prata',	'Colar, Index',	'Prata',	'Prata',	'Ajustável',	'20',	'15.00'),
('Brinco pequeno com dois corações, feito de aço inoxidável.',	'Brinco Pequeno 2 Corações Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Brinco pequeno redondo, feito de aço inoxidável.',	'Brinco Pequeno Redondo de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Brinco pequeno de coração, feito de aço inoxidável.',	'Brinco Pequeno Coração de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Brinco pequeno com pontos de luz, feito de aço inoxidável.',	'Brinco Pequeno Ponto de Luz de Aço Inoxidável',	'Brinco, Mais Vendidos',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Brinco pequeno de círculos, feito de aço inoxidável.',	'Brinco Pequeno Círculo de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Brinco pequeno com laços de nó, feito de aço inoxidável.',	'Brinco Pequeno Laço de Nó de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Brinco pequeno de folhas, feito de aço inoxidável.',	'Brinco Pequeno Folha de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Brinco pequeno de cruz, feito de aço inoxidável.',	'Brinco Pequeno Cruz de Aço Inoxidável',	'Brinco, Index',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Brinco pequeno de laços, feito de aço inoxidável.',	'Brinco Pequeno Laço de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Brinco pequeno com caudas de sereia, feito de aço inoxidável.',	'Brinco Pequeno Cauda de Sereia de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Brinco pequeno de flocos de neve, feito de aço inoxidável.',	'Brinco Pequeno Floco de Neve de Aço Inoxidável',	'Brinco, Index',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'5.00'),
('Mini argola com ponto de luz em formato de gota, feita de aço inoxidável.',	'Mini Argola de Aço Inoxidável com Ponto de Luz Formato Gota',	'Brinco',	'Prata',	'Aço Inoxidável, Joia',	'Pequeno',	'20',	'8.00'),
('Mini argola com três pontos de luz, feita de aço inoxidável.',	'Mini Argola de Aço Inoxidável com 3 Ponto de Luz',	'Brinco',	'Prata',	'Aço Inoxidável, Joia',	'Pequeno',	'20',	'8.00'),
('Argola grande com pedrarias, feita de aço inoxidável.',	'Argola Grande de Aço Inoxidável com Pedrarias',	'Brinco, Index',	'Prata',	'Aço Inoxidável, Joia',	'Grande',	'20',	'10.00'),
('Argola grande e fina, feita de aço inoxidável.',	'Argola Grande Fina de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Grande',	'20',	'8.00'),
('Argola média e fina feita de aço inoxidável.',	'Argola Média Fina de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Médio',	'20',	'5.00'),
('Argola média, feita de aço inoxidável.',	'Argola Média de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Médio',	'20',	'6.00'),
('Argola pequena detalhada, feita de aço inoxidável.',	'Argola Pequena Detalhada de Aço Inoxidável',	'Brinco, Index',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'8.00'),
('Argola tripla pequena, feita de aço inoxidável.',	'Argola Tripla Pequena de Aço Inoxidável',	'Brinco, Mais Vendidos',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'8.00'),
('Argola pequena, feita de aço inoxidável.',	'Argola Pequena de Aço Inoxidável',	'Brinco',	'Prata',	'Aço Inoxidável',	'Pequeno',	'20',	'6.00'),
('Porta joias para acompanhar com seu pedido.',	'Porta Joias Dauphine',	'Porta Joias',	'Rosa Claro, Rosa Choque',	'Poliéster',	'Pequeno',	'20',	'22.00');

